// scripts/claude-design/niches.js
// 50 niches × 10 section types = 500 prompts for the "Claude Design" pack.
// Each niche maps 1:1 to a /browse subcategory. Keep slugs stable.

module.exports = [
  // ---------- SaaS (12) ----------
  {
    slug: 'saas-b2b',
    name: 'B2B SaaS',
    icon: '🧰',
    description: 'Subscription software sold to teams and companies, billed seat-by-seat or per workspace.',
    audience: 'Heads of Ops and RevOps leaders at 50-500 person mid-market companies',
    productExample: 'A Notion-style workspace where product managers run async standups and roadmap reviews',
    brandTone: 'confident, calm, data-driven',
    painPoint: 'Trial-to-paid conversion stuck under 4% despite strong demo bookings',
    conversionGoal: 'Book a 20-minute demo with the founder',
    socialProofType: 'Logos of recognizable customers paired with named-buyer ROI quotes',
  },
  {
    slug: 'saas-b2c',
    name: 'B2C SaaS',
    icon: '📱',
    description: 'Self-serve consumer software with low-touch signup, monthly billing, and viral loops.',
    audience: 'Urban Indian millennials who pay for tools that save time on personal finance and habits',
    productExample: 'A Splitwise-meets-Cred app that auto-categorizes UPI spends and nudges weekly savings',
    brandTone: 'playful, friendly, slightly cheeky',
    painPoint: 'Day-7 retention drops below 18% after a strong launch week',
    conversionGoal: 'Free account creation with email or Google login',
    socialProofType: 'App store ratings, user count milestones, and Twitter screenshots',
  },
  {
    slug: 'saas-vertical',
    name: 'Vertical SaaS',
    icon: '🏗️',
    description: 'Industry-specific SaaS that replaces spreadsheets and legacy tools for one trade.',
    audience: 'Owners of mid-size construction firms in Tier-2 Indian cities running 5-30 active sites',
    productExample: 'A site-progress and material-tracking app for civil contractors with WhatsApp-first UX',
    brandTone: 'practical, no-nonsense, respectful of trade expertise',
    painPoint: 'Site supervisors still WhatsApp photos and Excel sheets, causing weekly billing disputes',
    conversionGoal: 'Schedule an onboarding call for one pilot project',
    socialProofType: 'Named contractor case studies with rupee-value savings and time-on-site cuts',
  },
  {
    slug: 'ai-ml-tool',
    name: 'AI/ML Tool',
    icon: '🤖',
    description: 'Generative-AI or ML-powered product where the model output is the core value prop.',
    audience: 'Marketing teams and solo creators tired of stitching together five AI tools',
    productExample: 'An AI ad-creative generator that produces 30 brand-locked Meta variants in 2 minutes',
    brandTone: 'futuristic, slightly bold, technically credible',
    painPoint: 'Marketers spend 6+ hours per campaign on creative variations and brand-safety checks',
    conversionGoal: 'Generate first asset inside the product (activation event)',
    socialProofType: 'Output side-by-sides, model benchmarks, and Product Hunt placement',
  },
  {
    slug: 'dev-tool',
    name: 'Developer Tool',
    icon: '⚙️',
    description: 'Tooling sold bottom-up to engineers via docs, CLI installs, and GitHub stars.',
    audience: 'Backend and platform engineers at fast-growing startups with 10-100 services in production',
    productExample: 'A drop-in observability SDK that auto-instruments distributed traces in 4 lines of code',
    brandTone: 'technical, dry, opinionated',
    painPoint: 'Setting up tracing eats two engineer-weeks and still leaves blind spots in async jobs',
    conversionGoal: 'Install the SDK and ship first trace to staging',
    socialProofType: 'GitHub stars, Hacker News threads, and quotes from staff engineers at known companies',
  },
  {
    slug: 'design-tool',
    name: 'Design Tool',
    icon: '🎨',
    description: 'Visual or collaborative design software for designers, founders, and creative teams.',
    audience: 'In-house product designers and freelancers building landing pages and mobile flows',
    productExample: 'A Figma plugin that turns wireframes into production React + Tailwind in one click',
    brandTone: 'crafted, expressive, design-first',
    painPoint: 'Designers ship 40% slower because handoff to dev still requires manual spec docs',
    conversionGoal: 'Install the plugin and run it on one frame',
    socialProofType: 'Designer testimonials, Dribbble shots made with the tool, agency logos',
  },
  {
    slug: 'productivity-app',
    name: 'Productivity App',
    icon: '✅',
    description: 'Task, notes, calendar, or focus tooling for individuals and small teams.',
    audience: 'Knowledge workers and founders juggling 4+ projects and constant context switching',
    productExample: 'A keyboard-driven task manager that auto-blocks calendar slots from your weekly goals',
    brandTone: 'crisp, minimal, almost meditative',
    painPoint: 'Users open 7 tabs to plan their day and abandon planning by 11am',
    conversionGoal: 'Sign up for the free plan and complete onboarding checklist',
    socialProofType: 'Power-user testimonials, productivity-blogger reviews, and visible streak counters',
  },
  {
    slug: 'crm',
    name: 'CRM',
    icon: '📇',
    description: 'Pipeline, contact, and deal-tracking software for sales-led businesses.',
    audience: 'Sales managers at 10-50 person services and SaaS companies switching off spreadsheets',
    productExample: 'A WhatsApp-first CRM for Indian D2C brands that logs every chat, call, and UPI payment link',
    brandTone: 'professional, energetic, sales-savvy',
    painPoint: 'Reps lose 12 hours a week to manual data entry and still forget to follow up',
    conversionGoal: 'Start a 14-day trial and import existing contacts',
    socialProofType: 'Pipeline screenshots, win-rate lift numbers, and named sales-leader quotes',
  },
  {
    slug: 'hr-tech',
    name: 'HR Tech',
    icon: '👥',
    description: 'Software for hiring, payroll, performance, or employee experience at growing companies.',
    audience: 'HR heads and founders at 30-300 person companies handling India payroll and PF/ESIC',
    productExample: 'A payroll + compliance platform that runs PF, PT, and TDS for Indian SMBs in one click',
    brandTone: 'reassuring, organized, compliance-aware',
    painPoint: 'Monthly payroll closing takes 3 days and one statutory miss costs lakhs in penalties',
    conversionGoal: 'Book a 30-minute demo with payroll consultant',
    socialProofType: 'CFO testimonials, compliance certifications, and named SMB customer logos',
  },
  {
    slug: 'martech',
    name: 'MarTech',
    icon: '📣',
    description: 'Marketing automation, email, lifecycle, or attribution software for growth teams.',
    audience: 'Growth and lifecycle marketers at D2C and SaaS brands running 6+ channels',
    productExample: 'A lifecycle platform that ties Razorpay revenue back to email, push, and WhatsApp campaigns',
    brandTone: 'sharp, growth-loop fluent, slightly aggressive',
    painPoint: 'Attribution gaps cause 30% of revenue to be credited to "direct" with no insight',
    conversionGoal: 'Connect data source and view first attribution dashboard',
    socialProofType: 'Cohort revenue lift charts, named CMO quotes, and benchmark reports',
  },
  {
    slug: 'adtech',
    name: 'AdTech',
    icon: '🎯',
    description: 'Ad buying, creative, or measurement platforms for performance marketers and agencies.',
    audience: 'Performance marketing leads spending Rs.10L+/month across Meta, Google, and YouTube',
    productExample: 'A creative-testing platform that auto-rotates Meta variants and kills losers under 1.5x ROAS',
    brandTone: 'punchy, ROI-obsessed, performance-marketer slang',
    painPoint: 'CPMs up 38% YoY while ROAS slid from 4x to 2.1x in one quarter',
    conversionGoal: 'Connect ad account and run first creative test',
    socialProofType: 'Ad-spend-managed numbers, ROAS lift case studies, and agency partner logos',
  },
  {
    slug: 'bi-analytics',
    name: 'BI / Analytics',
    icon: '📊',
    description: 'Dashboards, data warehousing, or self-serve analytics tools for data and ops teams.',
    audience: 'Data leads and ops managers at Series B+ companies tired of broken Looker dashboards',
    productExample: 'A self-serve metrics layer that lets non-SQL teams query revenue and cohort data in plain English',
    brandTone: 'clear-headed, analytical, quietly confident',
    painPoint: 'Data team fields 80+ ad-hoc requests a week and still ships dashboards 2 weeks late',
    conversionGoal: 'Connect warehouse and ship first dashboard',
    socialProofType: 'Data-leader testimonials, time-to-insight metrics, and warehouse partner badges',
  },

  // ---------- E-commerce (7) ----------
  {
    slug: 'd2c-brand',
    name: 'D2C Brand',
    icon: '🛍️',
    description: 'Single-brand direct-to-consumer storefront with strong product story and repeat purchase loop.',
    audience: 'Urban Indian women aged 24-38 buying premium personal-care from Instagram-native brands',
    productExample: 'A cold-pressed hair-oil brand using Ayurvedic recipes from Kerala, sold via own Shopify store',
    brandTone: 'warm, story-led, ingredient-honest',
    painPoint: 'Cost of acquisition crossed Rs.480 while AOV is stuck at Rs.690',
    conversionGoal: 'First-time purchase with welcome-offer discount',
    socialProofType: 'UGC reels, founder story, and ingredient-sourcing photos',
  },
  {
    slug: 'multi-product-store',
    name: 'Multi-Product Online Store',
    icon: '🏬',
    description: 'Single-vendor catalog store carrying many SKUs across related categories.',
    audience: 'Value-conscious shoppers in Indian metros and Tier-2 cities buying home and lifestyle goods',
    productExample: 'A home essentials store selling kitchenware, decor, and storage with 4-day Tier-2 delivery',
    brandTone: 'helpful, value-focused, family-friendly',
    painPoint: 'Cart abandonment hovers at 71% and bundle attach rate is below 8%',
    conversionGoal: 'Add to cart and complete checkout, ideally with a bundle',
    socialProofType: 'Verified review stars, bestseller badges, and "10,000+ orders shipped" counters',
  },
  {
    slug: 'marketplace',
    name: 'Marketplace',
    icon: '🛒',
    description: 'Two-sided platform connecting many independent sellers with buyers in a category.',
    audience: 'Hobbyists and gift buyers looking for handmade crafts from Indian artisans',
    productExample: 'A handmade-crafts marketplace onboarding 3,000 weavers and potters from rural India',
    brandTone: 'curatorial, community-led, slightly artisanal',
    painPoint: 'Liquidity is uneven, 40% of categories have fewer than 3 active sellers',
    conversionGoal: 'Buyer signup or seller application, depending on landing variant',
    socialProofType: 'Artisan profiles, GMV milestones, and press coverage in lifestyle media',
  },
  {
    slug: 'subscription-box',
    name: 'Subscription Box',
    icon: '📦',
    description: 'Curated recurring shipment of physical goods around a theme or category.',
    audience: 'Self-care-curious women aged 22-35 in Indian metros willing to spend Rs.999/month on discovery',
    productExample: 'A monthly clean-beauty box featuring 5 indie Indian brands, themed around a wellness ritual',
    brandTone: 'indulgent, curatorial, gift-like',
    painPoint: 'Month-3 churn is 38% because subscribers feel boxes get repetitive',
    conversionGoal: 'Subscribe to first month with prepaid 3-month option',
    socialProofType: 'Unboxing reels, subscriber count, and quotes from beauty editors',
  },
  {
    slug: 'fashion',
    name: 'Fashion',
    icon: '👗',
    description: 'Apparel or accessories brand selling seasonal drops, collections, or made-to-order pieces.',
    audience: 'Indian women 25-40 buying occasion-wear and modern ethnic for weddings and work',
    productExample: 'A modern-Indian-wear label doing made-to-measure kurta sets with Banarasi handlooms',
    brandTone: 'aesthetic, confident, culturally-rooted',
    painPoint: 'Returns and exchanges eat 22% of revenue due to fit and fabric mismatch',
    conversionGoal: 'Add to cart on a hero product, ideally with size guide engagement',
    socialProofType: 'Editorial lookbook shots, real-customer photos, and influencer wears',
  },
  {
    slug: 'beauty',
    name: 'Beauty',
    icon: '💄',
    description: 'Skincare, makeup, or haircare brand with ingredient transparency and routine-led storytelling.',
    audience: 'Indian women 18-35 with combination skin navigating climate and pollution concerns',
    productExample: 'A vitamin-C serum brand formulated for Indian humidity with 5% L-ascorbic acid',
    brandTone: 'science-credible, glowing, slightly editorial',
    painPoint: 'Repeat purchase rate stuck at 21% because users abandon routines after 3 weeks',
    conversionGoal: 'First-time purchase with routine-builder quiz completion',
    socialProofType: 'Dermatologist endorsements, before/after photos, and ingredient-deck transparency',
  },
  {
    slug: 'fnb-retail',
    name: 'F&B Retail',
    icon: '🍱',
    description: 'Packaged food, beverage, or specialty grocery brand sold online and in select stores.',
    audience: 'Health-conscious Indian families in metros buying clean-label snacks for kids',
    productExample: 'A millet-based kids snack brand with Rs.49 single-serve packs sold via Zepto, BB, and own site',
    brandTone: 'wholesome, parent-trusted, ingredient-proud',
    painPoint: 'Quick-commerce listing fees and discounts cut net margin to under 6%',
    conversionGoal: 'Buy a starter pack on the brand-owned store',
    socialProofType: 'Pediatrician quotes, FSSAI badges, and parent-community testimonials',
  },

  // ---------- Education (7) ----------
  {
    slug: 'edtech-app',
    name: 'EdTech App',
    icon: '📚',
    description: 'Mobile or web learning app with structured content, assessments, and progress tracking.',
    audience: 'Indian parents of class 6-10 students seeking after-school math and science help',
    productExample: 'A class 6-10 math practice app with NCERT-aligned worksheets and weekly Olympiad sets',
    brandTone: 'encouraging, parent-trusted, outcome-focused',
    painPoint: 'Active-user retention drops to 15% by week 4 once homework novelty wears off',
    conversionGoal: 'Free trial signup with first-week assessment completed',
    socialProofType: 'Score-improvement case studies, parent testimonials, and school partnerships',
  },
  {
    slug: 'online-course',
    name: 'Online Course',
    icon: '🎓',
    description: 'Self-paced or cohort-based digital course on a focused outcome, sold per seat.',
    audience: 'Mid-career professionals who want to add AI or data skills without quitting their job',
    productExample: 'A 6-week cohort on "Generative AI for product managers" with 4 live workshops',
    brandTone: 'authoritative, peer-led, outcome-promising',
    painPoint: 'Only 11% of self-paced learners finish, killing word-of-mouth referrals',
    conversionGoal: 'Enroll in next cohort with full payment',
    socialProofType: 'Alumni LinkedIn switches, instructor credibility, and cohort outcome metrics',
  },
  {
    slug: 'coaching-mentor',
    name: 'Coaching / Mentor',
    icon: '🧭',
    description: 'One-to-one or small-group coaching service sold as packages or monthly retainers.',
    audience: 'Mid-level managers preparing for senior PM or director roles at top tech companies',
    productExample: 'A 1:1 PM-to-Director coaching package with 8 sessions, mock interviews, and resume rewrite',
    brandTone: 'authoritative, warm, no-fluff',
    painPoint: 'Discovery calls convert at 22% because prospects cannot quantify program ROI',
    conversionGoal: 'Book a free 30-minute discovery call',
    socialProofType: 'Mentee promotion case studies, named-employer logos, and LinkedIn recommendations',
  },
  {
    slug: 'k12-school',
    name: 'K-12 Education',
    icon: '🏫',
    description: 'School, preschool, or daycare offering on-campus or hybrid education to children.',
    audience: 'Parents of 3-12 year olds in Tier-1 Indian cities choosing schools 6 months ahead of admission',
    productExample: 'A CBSE-aligned hybrid school in Bengaluru with project-based learning and 14:1 ratio',
    brandTone: 'trusted, modern, research-backed',
    painPoint: 'Only 1 in 4 campus-tour bookings converts to admission application',
    conversionGoal: 'Book a campus tour or attend an open house',
    socialProofType: 'Parent testimonials, faculty credentials, and student outcome stories',
  },
  {
    slug: 'test-prep',
    name: 'Test Prep',
    icon: '📝',
    description: 'Coaching or self-study product targeting a specific competitive or standardized exam.',
    audience: 'Indian aspirants preparing for UPSC, JEE, NEET, CAT, or GMAT in their first or second attempt',
    productExample: 'A CAT 2026 prep program with 240 hours of live classes, 60 mocks, and 1:1 mentorship',
    brandTone: 'rigorous, results-obsessed, faculty-credible',
    painPoint: 'Mock-test scores plateau by month 3 and 30% of students disengage',
    conversionGoal: 'Enroll in flagship program or take a free diagnostic test',
    socialProofType: 'Selection lists, percentile improvements, and named topper interviews',
  },
  {
    slug: 'coding-bootcamp',
    name: 'Coding Bootcamp',
    icon: '💻',
    description: 'Intensive software-engineering program with placement support, online or hybrid.',
    audience: 'Engineering grads and career-switchers in India seeking their first developer job',
    productExample: 'A 6-month full-stack bootcamp with placement guarantee and ISA payment option',
    brandTone: 'driven, outcomes-first, mentor-heavy',
    painPoint: 'Placement-guarantee timelines slip past 9 months for 35% of recent cohorts',
    conversionGoal: 'Apply for next cohort and complete admission test',
    socialProofType: 'Hiring company logos, alumni salary data, and placement-rate disclosures',
  },
  {
    slug: 'language-learning',
    name: 'Language Learning',
    icon: '🗣️',
    description: 'App, course, or coaching that helps adults reach conversational fluency in a new language.',
    audience: 'Indian professionals preparing for IELTS, TOEFL, or business-English fluency for global roles',
    productExample: 'A spoken-English coaching app with daily 15-min live tutor calls priced at Rs.999/month',
    brandTone: 'patient, confidence-building, globally-aspirational',
    painPoint: 'Learners hit a fluency plateau by week 5 and 28% cancel auto-renewal',
    conversionGoal: 'Start free trial with first speaking session booked',
    socialProofType: 'Before/after speaking samples, IELTS band-score lifts, and tutor credentials',
  },

  // ---------- Health & Wellness (5) ----------
  {
    slug: 'telehealth',
    name: 'Telehealth',
    icon: '🩺',
    description: 'Online consultation platform connecting patients with licensed doctors and specialists.',
    audience: 'Working professionals in Indian metros needing same-day specialist consults without travel',
    productExample: 'A dermatology telehealth service with 15-min video consults and Rs.499 follow-up window',
    brandTone: 'reassuring, clinical, privacy-first',
    painPoint: 'No-show rate on booked consultations is 26%, breaking doctor utilization economics',
    conversionGoal: 'Book and pay for first online consultation',
    socialProofType: 'Doctor credentials, patient ratings, and accreditation badges',
  },
  {
    slug: 'fitness-app',
    name: 'Fitness App',
    icon: '🏋️',
    description: 'Workout, training, or activity-tracking app sold as a monthly or yearly subscription.',
    audience: 'Indian adults 25-40 working desk jobs who train 3-4 times a week at home or a basic gym',
    productExample: 'A strength-training app with 12-week progressive plans and form-check video feedback',
    brandTone: 'motivating, no-shortcuts, evidence-led',
    painPoint: 'Day-30 active users drop below 22% because plans feel generic by week 3',
    conversionGoal: 'Start 7-day free trial with first workout completed',
    socialProofType: 'Transformation photos, coach credentials, and weekly active streak counts',
  },
  {
    slug: 'mental-health',
    name: 'Mental Health',
    icon: '🧠',
    description: 'Therapy, counseling, or self-care platform offering licensed support to adults.',
    audience: 'Urban Indian millennials managing anxiety and burnout but reluctant to walk into a clinic',
    productExample: 'An online therapy platform with 1,200 licensed Indian therapists and Rs.1,500 sessions',
    brandTone: 'gentle, non-judgmental, hopeful',
    painPoint: 'First-session bookings drop off at 41% due to long therapist-match wait times',
    conversionGoal: 'Take the matching quiz and book first session',
    socialProofType: 'Therapist credentials, anonymized patient quotes, and clinical-outcome data',
  },
  {
    slug: 'yoga-studio',
    name: 'Yoga Studio',
    icon: '🧘',
    description: 'Local or online yoga studio offering classes, workshops, and teacher-training programs.',
    audience: 'Adults 28-55 seeking flexibility, stress relief, and a real teacher relationship',
    productExample: 'A Bengaluru studio offering Iyengar, Ashtanga, and prenatal classes with 6-week beginner courses',
    brandTone: 'grounded, traditional, welcoming to beginners',
    painPoint: 'Trial-class to membership conversion sits at 14%, well below the 25% needed to break even',
    conversionGoal: 'Book a Rs.299 trial class or sign up for the 6-week beginner course',
    socialProofType: 'Teacher lineage, student testimonials, and years-of-practice counts',
  },
  {
    slug: 'nutrition-coaching',
    name: 'Nutrition Coaching',
    icon: '🥗',
    description: 'Personalized diet, weight, or wellness coaching from certified nutritionists.',
    audience: 'Indian adults 30-50 managing PCOS, diabetes, or 10-15 kg weight goals',
    productExample: 'A 12-week PCOS reversal program with a dedicated dietician and weekly WhatsApp check-ins',
    brandTone: 'compassionate, science-backed, sustainable',
    painPoint: 'Clients regain 60% of lost weight within 6 months of program completion',
    conversionGoal: 'Book a free 20-minute diet consult',
    socialProofType: 'Client transformation stories, lab-marker improvements, and dietician credentials',
  },

  // ---------- Local Services (8) ----------
  {
    slug: 'restaurant',
    name: 'Restaurant',
    icon: '🍽️',
    description: 'Single-location dine-in restaurant focused on a specific cuisine or experience.',
    audience: 'Couples and small groups in Indian metros looking for a memorable Friday or Saturday dinner',
    productExample: 'A 40-cover Italian trattoria in Mumbai serving fresh pasta and a 60-label Italian wine list',
    brandTone: 'warm, hospitable, food-passionate',
    painPoint: 'Weekday dinner covers run at 38% capacity, dragging weekly revenue 22% below target',
    conversionGoal: 'Book a table for tonight or this weekend',
    socialProofType: 'Critic reviews, Google rating, chef story, and Instagram food photography',
  },
  {
    slug: 'hotel-boutique-stay',
    name: 'Hotel / Boutique Stay',
    icon: '🏨',
    description: 'Independent boutique hotel, homestay, or villa with a strong location-specific experience.',
    audience: 'Indian and international travelers seeking experiential stays beyond chain hotels',
    productExample: 'A 9-room heritage homestay in Coorg with a coffee plantation walk and farm-to-table breakfast',
    brandTone: 'storied, intimate, place-rooted',
    painPoint: 'Direct-booking share is 18% with the rest going through OTAs at 22% commission',
    conversionGoal: 'Book a stay directly through the website',
    socialProofType: 'Guest reviews, travel-magazine features, and signature-experience photos',
  },
  {
    slug: 'salon',
    name: 'Salon',
    icon: '💇',
    description: 'Hair and beauty salon offering cut, color, styling, and care services in-studio.',
    audience: 'Women 22-45 in Indian metros willing to pay Rs.2,500+ for a senior-stylist service',
    productExample: 'A premium balayage and Brazilian-blowout salon in Delhi with senior-stylist pricing tiers',
    brandTone: 'polished, glam-forward, expertise-led',
    painPoint: 'Client repeat rate at 6 weeks is 33% versus the 55% needed for stylist retention',
    conversionGoal: 'Book an appointment online with a chosen stylist',
    socialProofType: 'Before/after gallery, stylist portfolios, and Google reviews',
  },
  {
    slug: 'spa',
    name: 'Spa',
    icon: '💆',
    description: 'Wellness and body-treatment spa offering massages, facials, and wellness packages.',
    audience: 'Working professionals 28-50 seeking monthly stress-relief or pre-wedding wellness packages',
    productExample: 'A Kerala-Ayurveda spa in Pune offering 7-day Panchakarma packages and 90-min Abhyanga sessions',
    brandTone: 'serene, sensory, restorative',
    painPoint: 'Weekday occupancy is 35% while weekends overflow with a 40-person waitlist',
    conversionGoal: 'Book a treatment online or buy a wellness package',
    socialProofType: 'Therapist training credentials, ambience photography, and Google reviews',
  },
  {
    slug: 'law-firm',
    name: 'Law Firm',
    icon: '⚖️',
    description: 'Boutique or specialist law firm serving startups, businesses, or individuals.',
    audience: 'Indian startup founders raising seed-to-Series-A who need fundraising and contract support',
    productExample: 'A Bengaluru boutique firm doing fundraising, ESOPs, and FEMA compliance for SaaS startups',
    brandTone: 'precise, trusted, founder-friendly',
    painPoint: 'Only 1 in 5 inbound consult requests converts to a paid retainer',
    conversionGoal: 'Book a 30-minute paid consultation',
    socialProofType: 'Named-deal logos, partner credentials, and founder testimonials',
  },
  {
    slug: 'accounting-firm',
    name: 'Accounting Firm',
    icon: '📒',
    description: 'CA or accounting firm offering tax, GST, and compliance services to SMBs and freelancers.',
    audience: 'Indian SMB owners and freelancers managing GST, TDS, and ITR with revenue of Rs.50L-10Cr',
    productExample: 'A virtual CA service offering monthly bookkeeping, GST filing, and ITR for Rs.4,999/month',
    brandTone: 'reliable, plain-English, deadline-aware',
    painPoint: 'Clients miss 1-2 GST deadlines a year, paying Rs.10K-Rs.50K each in penalties',
    conversionGoal: 'Book a free 20-minute compliance audit call',
    socialProofType: 'CA credentials, client retention years, and named SMB testimonials',
  },
  {
    slug: 'construction',
    name: 'Construction',
    icon: '🏗️',
    description: 'Residential or commercial construction firm handling design-build or contracting.',
    audience: 'Indian homeowners and small developers building 2,000-10,000 sqft residential plots',
    productExample: 'A design-build firm in Hyderabad delivering G+2 houses on a fixed Rs.1,800/sqft contract',
    brandTone: 'trustworthy, transparent, on-time-delivery focused',
    painPoint: 'Project schedules slip 35-90 days on average, eroding referrals and margin',
    conversionGoal: 'Book a free site visit and quotation',
    socialProofType: 'Completed-project gallery, owner testimonials, and material-source disclosures',
  },
  {
    slug: 'interior-design',
    name: 'Interior Design',
    icon: '🛋️',
    description: 'Interior design or turnkey home-styling firm for homeowners and small offices.',
    audience: 'First-time Indian homeowners furnishing 2-3BHK apartments with a Rs.6-25 lakh budget',
    productExample: 'A turnkey interiors firm offering 45-day delivery on 2BHKs with 10-year modular warranty',
    brandTone: 'tasteful, planner-friendly, value-clear',
    painPoint: 'Quote-to-signed-contract conversion is 18% because budgets balloon during scope discussions',
    conversionGoal: 'Book a free design consultation with 3D mockup',
    socialProofType: 'Completed-home portfolios, homeowner testimonials, and warranty terms',
  },

  // ---------- Real Estate (3) ----------
  {
    slug: 'property-portal',
    name: 'Property Listing Portal',
    icon: '🏘️',
    description: 'Marketplace for buyers, renters, and sellers to find and list residential or commercial property.',
    audience: 'Renters and first-time buyers in Indian metros searching for verified, no-broker listings',
    productExample: 'A no-broker rental platform with 90,000 verified listings across Bengaluru and Pune',
    brandTone: 'transparent, time-saving, anti-broker-fee',
    painPoint: '62% of inbound leads on free portals turn out to be unreachable or fake',
    conversionGoal: 'Browse listings and submit a contact request on a property',
    socialProofType: 'Verified-listing counts, user-volume milestones, and tenant testimonials',
  },
  {
    slug: 'co-living',
    name: 'Co-living',
    icon: '🛏️',
    description: 'Managed shared-accommodation brand renting fully furnished rooms with services included.',
    audience: 'Working professionals 22-30 moving cities for new jobs and unwilling to set up homes',
    productExample: 'A managed co-living brand in Bengaluru with 1,800 beds, daily housekeeping, and meal plans',
    brandTone: 'community-driven, hassle-free, urban-millennial',
    painPoint: 'Bed-occupancy averages 78% with onboarding-to-move-in dropoff at 32%',
    conversionGoal: 'Book a property tour or pay token-amount move-in deposit',
    socialProofType: 'Resident testimonials, occupancy numbers, and community-event photos',
  },
  {
    slug: 'agent-personal-site',
    name: 'Real Estate Agent Site',
    icon: '🔑',
    description: 'Personal-brand website for an individual real-estate agent or small-team broker.',
    audience: 'Buyers and sellers in a specific Indian micromarket looking for a known local expert',
    productExample: 'A South-Bombay luxury-realty agent site featuring Rs.5Cr+ apartment listings and seller services',
    brandTone: 'personal, locally-knowledgeable, trust-first',
    painPoint: 'Site converts only 1.5% of organic search traffic into qualified seller leads',
    conversionGoal: 'Book a buyer or seller consultation with the agent',
    socialProofType: 'Closed-deal value totals, named-client quotes, and years-in-market badge',
  },

  // ---------- Creator Economy (5) ----------
  {
    slug: 'podcast',
    name: 'Podcast',
    icon: '🎙️',
    description: 'Independent podcast with a defined niche, regular release cadence, and monetization mix.',
    audience: 'Indian founders and operators who listen to long-form interviews during commutes',
    productExample: 'A weekly Indian-startup podcast featuring 90-minute interviews with bootstrapped founders',
    brandTone: 'curious, thoughtful, conversational',
    painPoint: 'Newsletter signups from podcast listeners convert at only 0.8% of monthly downloads',
    conversionGoal: 'Subscribe to the show on Spotify, Apple Podcasts, or YouTube',
    socialProofType: 'Notable guest names, download milestones, and listener-review screenshots',
  },
  {
    slug: 'newsletter',
    name: 'Newsletter',
    icon: '📰',
    description: 'Independent email newsletter on a defined topic, sold via paid tier, sponsorships, or both.',
    audience: 'Mid-career Indian professionals wanting a 10-min weekly read on AI and software trends',
    productExample: 'A weekly newsletter analyzing 3 Indian startup deals and 1 global SaaS trend, with 28K subscribers',
    brandTone: 'analytical, opinionated, slightly insidery',
    painPoint: 'Free-to-paid conversion sits at 1.4% and sponsor renewals slipped to 60%',
    conversionGoal: 'Subscribe to the free list, with paid upgrade as secondary CTA',
    socialProofType: 'Open-rate stats, named-reader testimonials, and notable sponsor logos',
  },
  {
    slug: 'personal-brand',
    name: 'Personal Brand',
    icon: '⭐',
    description: 'Solo creator or expert selling courses, coaching, and speaking off a personal-name brand.',
    audience: 'LinkedIn followers of a marketing leader looking for cohort-based deep dives',
    productExample: 'A growth-marketer\'s personal site funneling LinkedIn audience into a Rs.49,999 cohort course',
    brandTone: 'first-person, opinionated, generous-with-frameworks',
    painPoint: 'Site visitors browse but only 0.6% join the email list, starving the funnel',
    conversionGoal: 'Subscribe to email list or apply to flagship cohort',
    socialProofType: 'LinkedIn follower counts, named past employers, and student testimonials',
  },
  {
    slug: 'author-book',
    name: 'Author / Book',
    icon: '📖',
    description: 'Single-author site promoting a non-fiction or fiction book with sales, talks, and lead magnets.',
    audience: 'Indian non-fiction readers and corporate L&D leaders buying for team distribution',
    productExample: 'A debut non-fiction book site for a leadership memoir with bulk-order and speaking inquiry options',
    brandTone: 'authoritative, story-led, slightly literary',
    painPoint: 'Bulk-order requests from corporates are only 4% of total book sales',
    conversionGoal: 'Pre-order or buy the book; secondary, request a speaking engagement',
    socialProofType: 'Endorsement quotes, bestseller lists, and corporate-bulk-order logos',
  },
  {
    slug: 'photographer',
    name: 'Photographer',
    icon: '📸',
    description: 'Independent photographer site for weddings, portraits, products, or commercial work.',
    audience: 'Indian couples planning destination weddings with a Rs.3-15 lakh photography budget',
    productExample: 'A destination-wedding photographer based in Goa with a 220-wedding portfolio and film add-ons',
    brandTone: 'cinematic, emotive, craft-proud',
    painPoint: 'Inquiry-to-booking conversion sits at 12%, hurt by slow email responses',
    conversionGoal: 'Submit an inquiry form with date, venue, and budget',
    socialProofType: 'Curated wedding albums, couple testimonials, and published-feature credits',
  },

  // ---------- Misc (3) ----------
  {
    slug: 'nonprofit',
    name: 'Nonprofit',
    icon: '🤝',
    description: 'Charity, NGO, or social-impact organization fundraising and recruiting volunteers online.',
    audience: 'Indian salaried donors aged 28-55 making Rs.500-Rs.10,000 monthly donations under 80G',
    productExample: 'An NGO funding rural-school libraries across 320 villages in Madhya Pradesh and Bihar',
    brandTone: 'sincere, impact-led, donor-respecting',
    painPoint: 'Recurring-donor share is only 18% of donor base, making annual fundraising volatile',
    conversionGoal: 'Set up a monthly recurring donation',
    socialProofType: 'Beneficiary stories, audited impact numbers, and 80G compliance badges',
  },
  {
    slug: 'event-conference',
    name: 'Event / Conference',
    icon: '🎟️',
    description: 'Single-event or recurring conference site selling tickets, sponsorships, and speaker slots.',
    audience: 'Indian product and growth professionals who travel for one or two flagship conferences a year',
    productExample: 'A 2-day SaaS conference in Bengaluru with 60 speakers, 1,800 attendees, and tiered passes',
    brandTone: 'high-energy, FOMO-inducing, community-led',
    painPoint: 'Early-bird tickets sell well but full-price tier converts at only 1.1% of site traffic',
    conversionGoal: 'Buy a delegate ticket; secondary, apply to speak or sponsor',
    socialProofType: 'Past-edition photo reels, headline-speaker bios, and sponsor logos',
  },
  {
    slug: 'mobile-app',
    name: 'Mobile App',
    icon: '📲',
    description: 'Standalone consumer mobile app using a landing page to drive App Store and Play Store installs.',
    audience: 'Indian Gen-Z users 18-26 who discover new apps via Instagram reels and TikTok-style content',
    productExample: 'An AI photo-styling app that turns selfies into 30 styled portraits for Rs.99 a pack',
    brandTone: 'youthful, trendy, screenshot-driven',
    painPoint: 'Click-to-install rate from paid social sits at 3.2%, well below the 8% needed for ROAS',
    conversionGoal: 'Tap "Install" and complete App Store or Play Store download',
    socialProofType: 'App store rating, install-count milestones, and UGC reels of in-app outputs',
  },
];
